<?php

namespace DoctrineProxies\__CG__\orm\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Armure extends \orm\Entity\Armure implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'qualite', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'nom', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'vie', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'resilience', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'resistance', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'malusEsquive', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'amelioration1', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'amelioration2', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'amelioration3'];
        }

        return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'qualite', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'nom', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'vie', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'resilience', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'resistance', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'malusEsquive', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'amelioration1', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'amelioration2', '' . "\0" . 'orm\\Entity\\Armure' . "\0" . 'amelioration3'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Armure $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualite($qualite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualite', [$qualite]);

        return parent::setQualite($qualite);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualite', []);

        return parent::getQualite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setVie($vie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVie', [$vie]);

        return parent::setVie($vie);
    }

    /**
     * {@inheritDoc}
     */
    public function getVie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVie', []);

        return parent::getVie();
    }

    /**
     * {@inheritDoc}
     */
    public function setResilience($resilience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResilience', [$resilience]);

        return parent::setResilience($resilience);
    }

    /**
     * {@inheritDoc}
     */
    public function getResilience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResilience', []);

        return parent::getResilience();
    }

    /**
     * {@inheritDoc}
     */
    public function setResistance($resistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResistance', [$resistance]);

        return parent::setResistance($resistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getResistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResistance', []);

        return parent::getResistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setMalusEsquive($malusEsquive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMalusEsquive', [$malusEsquive]);

        return parent::setMalusEsquive($malusEsquive);
    }

    /**
     * {@inheritDoc}
     */
    public function getMalusEsquive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMalusEsquive', []);

        return parent::getMalusEsquive();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmelioration1($amelioration1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmelioration1', [$amelioration1]);

        return parent::setAmelioration1($amelioration1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmelioration1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmelioration1', []);

        return parent::getAmelioration1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmelioration2($amelioration2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmelioration2', [$amelioration2]);

        return parent::setAmelioration2($amelioration2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmelioration2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmelioration2', []);

        return parent::getAmelioration2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmelioration3($amelioration3 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmelioration3', [$amelioration3]);

        return parent::setAmelioration3($amelioration3);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmelioration3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmelioration3', []);

        return parent::getAmelioration3();
    }

    /**
     * {@inheritDoc}
     */
    public function copyFrom($armure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyFrom', [$armure]);

        return parent::copyFrom($armure);
    }

}
