<?php

namespace DoctrineProxies\__CG__\orm\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CharacterMagie extends \orm\Entity\CharacterMagie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\CharacterMagie' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\CharacterMagie' . "\0" . 'character'];
        }

        return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\CharacterMagie' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\CharacterMagie' . "\0" . 'character'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CharacterMagie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMagie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagie', []);

        return parent::getMagie();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagie(\orm\Entity\Magie $magie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagie', [$magie]);

        return parent::setMagie($magie);
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacter(\orm\Entity\Character $character = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacter', [$character]);

        return parent::setCharacter($character);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacter', []);

        return parent::getCharacter();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDegats($degats = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDegats', [$degats]);

        return parent::setDegats($degats);
    }

    /**
     * {@inheritDoc}
     */
    public function getDegats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDegats', []);

        return parent::getDegats();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritique($critique = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritique', [$critique]);

        return parent::setCritique($critique);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritique', []);

        return parent::getCritique();
    }

    /**
     * {@inheritDoc}
     */
    public function setMalus($malus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMalus', [$malus]);

        return parent::setMalus($malus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMalus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMalus', []);

        return parent::getMalus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMana($mana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMana', [$mana]);

        return parent::setMana($mana);
    }

    /**
     * {@inheritDoc}
     */
    public function getMana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMana', []);

        return parent::getMana();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEffet($effet = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEffet', [$effet]);

        return parent::setEffet($effet);
    }

    /**
     * {@inheritDoc}
     */
    public function getEffet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEffet', []);

        return parent::getEffet();
    }

    /**
     * {@inheritDoc}
     */
    public function copyFrom($magie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyFrom', [$magie]);

        return parent::copyFrom($magie);
    }

}
