<?php

namespace DoctrineProxies\__CG__\orm\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \orm\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'nameContact', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'numberTel', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'chance', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'character', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'character_id'];
        }

        return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'nameContact', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'numberTel', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'chance', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'character', '' . "\0" . 'orm\\Entity\\Contact' . "\0" . 'character_id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameContact($nameContact = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameContact', [$nameContact]);

        return parent::setNameContact($nameContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameContact', []);

        return parent::getNameContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberTel($numberTel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberTel', [$numberTel]);

        return parent::setNumberTel($numberTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberTel', []);

        return parent::getNumberTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setChance($chance = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChance', [$chance]);

        return parent::setChance($chance);
    }

    /**
     * {@inheritDoc}
     */
    public function getChance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChance', []);

        return parent::getChance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacter_id($character_id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacter_id', [$character_id]);

        return parent::setCharacter_id($character_id);
    }

}
