<?php

namespace DoctrineProxies\__CG__\orm\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Arme extends \orm\Entity\Arme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'qualite', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'nom', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'degats', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'critique', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'resistance', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'bonusParade', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'degatSurRes', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'tauxDestruction', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'amelioration'];
        }

        return ['__isInitialized__', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'id', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'qualite', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'nom', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'degats', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'critique', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'resistance', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'bonusParade', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'degatSurRes', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'tauxDestruction', '' . "\0" . 'orm\\Entity\\Arme' . "\0" . 'amelioration'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Arme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualite($qualite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualite', [$qualite]);

        return parent::setQualite($qualite);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualite', []);

        return parent::getQualite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDegats($degats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDegats', [$degats]);

        return parent::setDegats($degats);
    }

    /**
     * {@inheritDoc}
     */
    public function getDegats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDegats', []);

        return parent::getDegats();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritique($critique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritique', [$critique]);

        return parent::setCritique($critique);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritique', []);

        return parent::getCritique();
    }

    /**
     * {@inheritDoc}
     */
    public function setResistance($resistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResistance', [$resistance]);

        return parent::setResistance($resistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getResistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResistance', []);

        return parent::getResistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setBonusParade($bonusParade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBonusParade', [$bonusParade]);

        return parent::setBonusParade($bonusParade);
    }

    /**
     * {@inheritDoc}
     */
    public function getBonusParade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonusParade', []);

        return parent::getBonusParade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDegatSurRes($degatSurRes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDegatSurRes', [$degatSurRes]);

        return parent::setDegatSurRes($degatSurRes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDegatSurRes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDegatSurRes', []);

        return parent::getDegatSurRes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxDestruction($tauxDestruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxDestruction', [$tauxDestruction]);

        return parent::setTauxDestruction($tauxDestruction);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxDestruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxDestruction', []);

        return parent::getTauxDestruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmelioration($amelioration = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmelioration', [$amelioration]);

        return parent::setAmelioration($amelioration);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmelioration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmelioration', []);

        return parent::getAmelioration();
    }

    /**
     * {@inheritDoc}
     */
    public function copyFrom($arme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyFrom', [$arme]);

        return parent::copyFrom($arme);
    }

}
